[project]
authors = ["Konrad Handrick <konradha@yahoo.com>"]
channels = ["conda-forge"]
description = ""
name = "STELLOPT"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
gcc = "*"
gfortran = "*"
cmake = "*"
make = "*"
openmpi = ">=5.0.6,<6"
netcdf4 = "*"
hdf5 = {version="*", build="mpi_openmpi*"}
lapack = "*"
blas = "*"
openmpi-mpifort = "*"
netcdf-fortran = "*"
scalapack = "*"

[tasks]
build = { cmd = "bash build.sh" }
